### PR TITLE
updated astro & dependencies

### PR DESCRIPTION
**Pull request by fountainpen**

### CODE REVIEW

**Comment by BryceRussell** [comment]
Thanks for opening a PR on this @fountainpen! Do you mind also updating the `package-lock.json`?

**Comment by fountainpen** [comment]
that's a lot of things to update 💀

**Comment by fountainpen** [comment]
there are some github bots that do updating stuff.

**Comment by BryceRussell** [comment]
This repo is a bit old and I don't have any GitHub bots setup. Updating the `package-lock.json` should be as simple as deleting the old one and running `npm i` to generate a new one.

**Comment by fountainpen** [comment]
I edited this on github directly. dont really have git. :-/

**Comment by BryceRussell** [comment]
Ahh I see, updating the dependencies to Astro v3.0 involves a bit more than just updating the versions in `package.json`. [3.0 has a bunch of changes](https://docs.astro.build/en/guides/upgrade-to/v3/) so the repo needs to be updated to reflect these changes and if any of them apply and then you would want to run it locally to confirm that everything works. (and update `package-lock.json`)

**Comment by BryceRussell** [comment]
@fountainpen I am going to go ahead and close this for now, but please feel free to open an issue about this

**Pull request closed without merging**
